import json
import base64
import mimetypes
import re
from typing import List, Dict, Any, Optional
from datetime import datetime
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse


class NotebookService:
    """Service for generating and exporting Jupyter Notebooks."""
    
    def __init__(self):
        self.notebook_version = 4
    
    def create_notebook(
        self,
        conversation_title: str,
        messages: List[Dict[str, Any]],
        tool_calls: List[Dict[str, Any]],
        images: List[str] = None
    ) -> Dict[str, Any]:
        """Create a Jupyter Notebook from conversation history."""
        
        cells = []
        
        # Add title cell
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"# {conversation_title}\n",
                f"\n",
                f"Generated by LAMBDA on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
                f"\n",
                f"---\n"
            ]
        })
        
        # Process messages and tool calls
        tool_call_idx = 0
        execution_count = 1
        
        for msg in messages:
            if msg.get("role") == "user":
                # User query
                cells.append({
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [
                        f"## User Query\n",
                        f"\n",
                        f"{msg.get('content', '')}\n"
                    ]
                })
                
            elif msg.get("role") == "assistant":
                # Assistant response
                content = self._clean_assistant_content(msg.get("content", ""))
                
                # Check if this message has tool calls
                tool_calls_data = msg.get("tool_calls")
                if tool_calls_data:
                    try:
                        if isinstance(tool_calls_data, str):
                            tool_calls_data = json.loads(tool_calls_data)
                    except:
                        tool_calls_data = []
                
                if tool_calls_data:
                    # Add assistant's main response
                    if content:
                        cells.append({
                            "cell_type": "markdown",
                            "metadata": {},
                            "source": [f"{content}\n"]
                        })
                    
                    # Add execution details
                    for tc in tool_calls_data:
                        tool_name = tc.get("function", {}).get("name", "unknown")
                        tool_args = tc.get("function", {}).get("arguments", "{}")
                        
                        try:
                            args = json.loads(tool_args)
                            code = args.get("code", "")
                        except:
                            code = tool_args
                        
                        if code:
                            result = tc.get("result")
                            if not result and tool_call_idx < len(tool_calls):
                                tc_result = tool_calls[tool_call_idx]
                                result = tc_result.get("result")

                            outputs = self._build_outputs(result or {})

                            # Add code cell
                            cells.append({
                                "cell_type": "code",
                                "execution_count": execution_count,
                                "metadata": {},
                                "outputs": outputs,
                                "source": [line + "\n" for line in code.split("\n")]
                            })
                            execution_count += 1

                        tool_call_idx += 1
                else:
                    # Simple text response without tool calls
                    if content:
                        cells.append({
                            "cell_type": "markdown",
                            "metadata": {},
                            "source": [f"{content}\n"]
                        })
        
        # Create notebook structure
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {
                        "name": "ipython",
                        "version": 3
                    },
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.10.0"
                }
            },
            "nbformat": self.notebook_version,
            "nbformat_minor": 4
        }
        
        return notebook

    def _clean_assistant_content(self, content: str) -> str:
        """Remove frontend-only markers and execution summaries from assistant text."""
        if not content:
            return ""

        content = re.sub(r'<!--COLLAPSIBLE:Analyze details-->[\s\S]*?<!--END_COLLAPSIBLE-->', '', content)
        content = re.sub(r'<!--FILES:[\s\S]*?-->', '', content)
        content = re.sub(r'<!--[\s\S]*?-->', '', content)
        return content.strip()

    def _build_outputs(self, result: Dict[str, Any]) -> List[Dict[str, Any]]:
        outputs: List[Dict[str, Any]] = []
        if not result:
            return outputs

        stdout = result.get("stdout") or result.get("output") or ""
        stdout = self._clean_execution_text(stdout)
        if stdout:
            outputs.append({
                "name": "stdout",
                "output_type": "stream",
                "text": self._to_notebook_lines(stdout)
            })

        stderr = result.get("stderr") or ""
        stderr = self._clean_execution_text(stderr)
        if stderr:
            outputs.append({
                "name": "stderr",
                "output_type": "stream",
                "text": self._to_notebook_lines(stderr)
            })

        image_refs = list(result.get("images") or [])
        for file_info in result.get("generated_files") or []:
            if not isinstance(file_info, dict):
                continue
            file_type = (file_info.get("type") or file_info.get("category") or "").lower()
            filename = (file_info.get("filename") or file_info.get("name") or "").lower()
            if file_type == "image" or filename.endswith((".png", ".jpg", ".jpeg", ".svg")):
                image_ref = (
                    file_info.get("url")
                    or file_info.get("file_path")
                    or file_info.get("path")
                    or file_info.get("oss_url")
                )
                if image_ref:
                    image_refs.append(image_ref)

        seen_refs = set()
        for img_ref in image_refs:
            if not img_ref or img_ref in seen_refs:
                continue
            seen_refs.add(img_ref)
            image_output = self._image_ref_to_output(img_ref)
            if image_output:
                outputs.append(image_output)

        return outputs

    def _clean_execution_text(self, text: str) -> str:
        if not text:
            return ""
        cleaned_lines = []
        for line in text.splitlines():
            if "[IMAGE_SAVED]" in line or "[CAPTURED_IMAGES]" in line:
                continue
            cleaned_lines.append(line)
        return "\n".join(cleaned_lines).strip()

    def _to_notebook_lines(self, text: str) -> List[str]:
        if not text:
            return []
        return [line + "\n" for line in text.splitlines()]

    def _image_ref_to_output(self, ref: str) -> Optional[Dict[str, Any]]:
        try:
            image_bytes, media_type = self._read_image_reference(ref)
            if not image_bytes:
                return None

            if not media_type or media_type == "application/octet-stream":
                guessed_type, _ = mimetypes.guess_type(ref)
                media_type = guessed_type or "image/png"
            if media_type not in {"image/png", "image/jpeg", "image/svg+xml"}:
                return None

            return {
                "data": {
                    media_type: base64.b64encode(image_bytes).decode("ascii"),
                    "text/plain": ["<IPython.core.display.Image object>"]
                },
                "metadata": {},
                "output_type": "display_data"
            }
        except Exception as e:
            print(f"Error embedding notebook image {ref}: {e}")
            return None

    def _read_image_reference(self, ref: str) -> tuple[bytes | None, str | None]:
        if ref.startswith("data:image/"):
            header, data = ref.split(",", 1)
            media_type = header.split(";", 1)[0].replace("data:", "")
            return base64.b64decode(data), media_type

        content_url_path = self._extract_local_content_path(ref)
        if content_url_path:
            path_ref = Path(content_url_path)
            if path_ref.exists():
                media_type, _ = mimetypes.guess_type(str(path_ref))
                return path_ref.read_bytes(), media_type or "application/octet-stream"

        object_name = self._extract_proxy_or_oss_object_name(ref)
        if object_name:
            from app.services.oss_service import get_oss_service

            content = get_oss_service().bucket.get_object(object_name).read()
            media_type, _ = mimetypes.guess_type(object_name)
            return content, media_type or "application/octet-stream"

        path_ref = Path(ref[1:] if ref.startswith("/") else ref)
        possible_paths = [
            path_ref,
            Path("./data") / path_ref,
            Path("./data/images") / path_ref.name,
        ]
        for path in possible_paths:
            if path.exists():
                media_type, _ = mimetypes.guess_type(str(path))
                return path.read_bytes(), media_type or "application/octet-stream"

        return None, None

    def _extract_local_content_path(self, ref: str) -> str:
        if "/api/v1/files/content" not in ref:
            return ""

        parsed = urlparse(ref)
        path_values = parse_qs(parsed.query).get("url", [])
        return unquote(path_values[0]) if path_values else ""

    def _extract_proxy_or_oss_object_name(self, ref: str) -> str:
        allowed_prefixes = ("generated/", "uploads/", "latex/")

        if ref.startswith("/api/v1/files/proxy-object") or "/api/v1/files/proxy-object" in ref:
            parsed = urlparse(ref)
            path_values = parse_qs(parsed.query).get("path", [])
            object_name = unquote(path_values[0]) if path_values else ""
        elif "lambda-app-prod.oss-cn-hongkong.aliyuncs.com/" in ref:
            parsed = urlparse(ref)
            object_name = unquote(parsed.path.lstrip("/"))
        else:
            object_name = unquote(ref.lstrip("/"))

        object_name = unquote(object_name)
        return object_name if object_name.startswith(allowed_prefixes) else ""
    
    def export_notebook(
        self,
        conversation_title: str,
        messages: List[Dict[str, Any]],
        tool_calls: List[Dict[str, Any]],
        output_path: str
    ) -> str:
        """Export conversation as a Jupyter Notebook file."""
        
        notebook = self.create_notebook(conversation_title, messages, tool_calls)
        
        # Ensure directory exists
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        # Write notebook
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(notebook, f, indent=2, ensure_ascii=False)
        
        return output_path
